include: package:lint/analysis_options.yaml

linter:
  rules:
    always_use_package_imports: false
    depend_on_referenced_packages: false

analyzer:
  exclude:
    - lib/generated_plugin_registrant.dart
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
  strong-mode:
    implicit-casts: true
    implicit-dynamic: true