name: build

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, reopened, closed ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  FLUTTER_VERSION: '2.10.5' 

jobs:
  analyze-test:
    if: github.event_name != 'pull_request' || github.event.action == 'opened' || github.event.action == 'reopened' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{env.FLUTTER_VERSION}}
          channel: 'stable'
          cache: true
          architecture: x64
      - run: flutter pub get
      - run: flutter pub run build_runner build
      - run: flutter analyze
    # - run: flutter test // TODO: create tests
  build-macos:
    needs: [ analyze-test ]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{env.FLUTTER_VERSION}}
          channel: 'stable'
          cache: true
          architecture: x64
      - run: flutter pub get
      - run: flutter pub run build_runner build
      - run: flutter config --enable-macos-desktop
      - name: Install app dmg
        run: npm install -g appdmg
      - name: Create assets
        run: flutter pub run flutter_distributor:main package --platform macos --targets dmg
      - name: Upload MacOS artifact
        uses: actions/upload-artifact@v3
        with:
          name: ac_companion-macos
          path: dist/**/*.dmg
  build-linux:
    needs: [ analyze-test ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{env.FLUTTER_VERSION}}
          channel: 'stable'
          cache: true
          architecture: x64
      - run: flutter pub get
      - run: flutter pub run build_runner build
      - run: flutter config --enable-linux-desktop
      - name: Install linux flutter sdk requirements
        run: sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev
      - name: Install flutter secure storage requirements
        run: sudo apt-get install libsecret-1-dev libjsoncpp-dev libsecret-1-0
      - name: Create assets
        run: flutter pub run flutter_distributor:main package --platform linux --targets deb,zip
      - name: Upload Linux artifact
        uses: actions/upload-artifact@v3
        with:
          name: ac_companion-linux
          path: |
            dist/**/*.deb
            dist/**/*.zip

  build-windows:
    needs: [ analyze-test ]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{env.FLUTTER_VERSION}}
          channel: 'stable'
          cache: true
          architecture: x64
      - run: flutter pub get
      - run: flutter pub run build_runner build
      - run: flutter config --enable-windows-desktop
      - name: Create assets
        run: flutter pub run flutter_distributor:main package --platform windows --targets msix,exe
      - name: Upload windows artifact
        uses: actions/upload-artifact@v3
        with:
          name: ac_companion-windows
          path: |
            dist/**/*.msix
            dist/**/*.exe
  deploy:
    if: startsWith(github.head_ref, 'release/') && github.event.pull_request.merged == true
    needs: [ build-macos, build-windows, build-linux ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Retrieve Version Number
        id: versions
        run: |
          APP_VERSION=$(more pubspec.yaml | grep version: | cut -d ' ' -f2)
          echo $APP_VERSION
          echo "::set-output name=version::$(echo $APP_VERSION)"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.versions.outputs.version }}
          release_name: Release ${{ steps.versions.outputs.version }}
          body: |
            Release Notes
          draft: false
          prerelease: false
      - name: Download MacOS assets
        uses: actions/download-artifact@v3
        with:
          name: ac_companion-macos
      - name: Upload MacOS dmg
        id: upload-release-macos-dmg
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "./${{ steps.versions.outputs.version }}/appcenter_companion-${{ steps.versions.outputs.version }}-macos.dmg"
          asset_name: "appcenter_companion-${{ steps.versions.outputs.version }}-macos.dmg"
          asset_content_type: application/octet-stream
      - name: Download Linux assets
        uses: actions/download-artifact@v3
        with:
          name: ac_companion-linux
      - name: Upload Linux deb
        id: upload-asset-linux-deb
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "./${{ steps.versions.outputs.version }}/appcenter_companion-${{ steps.versions.outputs.version }}-linux_deb.deb"
          asset_name: "appcenter_companion-${{ steps.versions.outputs.version }}-linux.deb"
          asset_content_type: application/octet-stream
      - name: Upload Linux zip
        id: upload-release-linux-zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "./${{ steps.versions.outputs.version }}/appcenter_companion-${{ steps.versions.outputs.version }}-linux.zip"
          asset_name: "appcenter_companion-${{ steps.versions.outputs.version }}-linux.zip"
          asset_content_type: application/octet-stream
      - name: Download Windows assets
        uses: actions/download-artifact@v3
        with:
          name: ac_companion-windows
      - name: Upload Windows msix
        id: upload-release-windows-msix
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "./${{ steps.versions.outputs.version }}/appcenter_companion-${{ steps.versions.outputs.version }}-windows.msix"
          asset_name: "appcenter_companion-${{ steps.versions.outputs.version }}-windows.msix"
          asset_content_type: application/octet-stream
      - name: Upload Windows exe
        id: upload-release-windows-exe
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "./${{ steps.versions.outputs.version }}/appcenter_companion-${{ steps.versions.outputs.version }}-windows-setup.exe"
          asset_name: "appcenter_companion-${{ steps.versions.outputs.version }}-windows-setup.exe"
          asset_content_type: application/octet-stream